export const alfabetoForca: string[] = [
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 
        '+', '#'
    ];

export const MAX_TRIES = 6;
interface PalavrasObject{
[key: string]: string[]
}

export const forcaPalavras: PalavrasObject = {
        "Animais": [
                "Elefante",
                "Girafa",
                "Rinoceronte",
                "Canguru",
                "Golfinho",
                "Tucano",
                "Arara",
                "Leão",
                "Pinguim",
                "Camaleão",
                "Cachorro",
                "Gato",
                "Coelho",
                "Pássaro",
                "Rato",
                "Cavalo",
                "Vaca",
                "Porco",
                "Cabra",
        ],
        "Profissões": [
                "Arquiteto",
                "Bibliotecário",
                "Engenheiro",
                "Nutricionista",
                "Psicólogo",
                "Astrônomo",
                "Programador",
                "Contador",
                "Designer",
                "Eletricista",
                "Enfermeiro",
                "Advogado",
                "Cirurgião",
                "Pedreiro",
        ],
        "Frutas": [
                "Abacaxi",
                "Cereja",
                "Framboesa",
                "Tangerina",
                "Banana",
                "Maçã",
                "Mamão",
                "Ameixa",
                "Goiaba",
                "Melancia",
                "Abacate",
                "Melão",
                "Laranja",
                "Limão",
                "Pinha",
                "Kiwi",
                "Pêssego",
                "Morango",
                "Pitaya",
        ],
        "Cores": [
                "Vermelho",
                "Bronze",
                "Lilás",
                "Marrom",
                "Laranja",
                "Verde",
                "Cinza",
                "Dourado",
                "Lilás",
                "Azul",
                "Prata",
                "Amarelo",
                "Roxo",
                "Rosa",
                "Bege",
                "Branco",
                "Preto"
        ],
        "Países": [
                "Austrália",
                "Dinamarca",
                "Singapura",
                "Marrocos",
                "Indonésia",
                "Noruega",
                "Grécia",
                "Hungria",
                "Lituânia",
                "Suíça",
                "Brasil",
                "Argentina",
                "Uruguai",
                "Paraguai",
                "Bolívia",
                "Peru",
                "Ecuador",
                "Cuba",
                "Estados Unidos",
                "Canadá",
                "México",
                "Honduras",
                "Belize",
                "África do Sul",
                "Portugal",
                "Espanha",
                "Japão",
                "China",
                "Coréia do Sul"
        ],
        "Objetos": [
                "Calculadora",
                "Lanterna",
                "Parafuso",
                "Tesoura",
                "Mochila",
                "Caneca",
                "Almofada",
                "Relógio",
                "Espelho",
                "Caderno",
                "Teclado",
                "Lápis",
                "Faca",
                "Mesa"
        ],
        "Programação": [
                "Python",
                "Java",
                "C",
                "C++",
                "JavaScript",
                "TypeScript",
                "C#",
                "Cobol",
                "Pascal",
                "HTML",
                "CSS",
                "Docker",
                "Git",
                "GitHub",
                "Rust",
                "Swift",
                "Ruby on Rails",
                "Go",
                "Lua",
                "Julia",
                "R",
                "NodeJS",
                "WebAssembly",
                "Elm",
                "Forth",
                "APL",
                "F#",
                "Brainfuck",
                "Vala",
                "Crystal",
                "Whitespace",
                "Racket",
                "Common Lisp",
                "Haskell",
                "Smalltalk",
                "Bash",
                "B",
                "D",
                "AssemblyScript",
                "Clojure",
                "Kotlin",
                "Elixir",
                "OCaml",
                "GDScript",
                "Groovy",
                "Batch",
                "VimScript",
                "Zig",
                "PLSQL"
        ]
};

